
const tracks=JSON.parse(document.querySelector('#tracks').textContent), byId=new Map(tracks.map((t,i)=>[t.id,i]));
const key='guqin_full_recordings_v1'; let state={};try{state=JSON.parse(localStorage.getItem(key)||'{}')}catch{};
let current=-1, visible=[]; const $=s=>document.querySelector(s), audio=$('#audio');
const labels={keep:'整首可用',mood:'有氛围',partial:'部分可用',reject:'不适合'};
const group=t=>t.priority==='其他候选'?'other':'approved';
function save(){localStorage.setItem(key,JSON.stringify(state))}
function filtered(){const q=$('#search').value.trim().toLowerCase(),g=$('#group').value,f=$('#filter').value;return tracks.map((t,i)=>i).filter(i=>{const t=tracks[i],d=state[t.id]?.decision||'';return(g==='all'||group(t)===g)&&(f==='all'||(f==='unrated'?!d:d===f))&&(!q||(t.artist+' '+t.title+' '+t.id).toLowerCase().includes(q))})}
function render(){visible=filtered();const total=Object.values(state).filter(x=>x?.decision).length;$('#count').textContent=`已判 ${total} / ${tracks.length} · 当前显示 ${visible.length}`;$('#list').innerHTML=visible.map((i,n)=>{const t=tracks[i],d=state[t.id]?.decision||'',cls=d==='keep'?'good':d==='reject'?'bad':d?'maybe':'';return `<div class="row ${i===current?'active':''}" tabindex="0" data-index="${i}"><span class="num">${n+1}</span><span><strong>${esc(t.artist)} · ${esc(t.title)}</strong><span class="meta">${esc(t.album)} · ${Math.round(t.seconds/60)} 分钟 · ${esc(t.priority)}</span></span><span class="pill ${cls}">${labels[d]||'待判断'}</span></div>`}).join('');}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function choose(i,play=true){if(i<0||i>=tracks.length)return;const changed=current!==i;current=i;const t=tracks[i];$('#place').textContent=t.priority+' · '+t.album;$('#title').textContent=t.artist+' · '+t.title;$('#facts').textContent=`约 ${Math.floor(t.seconds/60)} 分 ${String(t.seconds%60).padStart(2,'0')} 秒 · ${t.id}`;$('#prior').textContent=t.prior?`先前短片段判断：${t.prior}${t.priorIssues?'；'+t.priorIssues:''}${t.priorNote?'；'+t.priorNote:''}。尚未代表整曲已通过。`:'先前没有逐曲听感判断。';$('#comment').value=state[t.id]?.comment||'';$('#ranges').value=state[t.id]?.ranges||'';$('#signal').textContent=`整曲机器提示：${t.clipSeconds??'未检查'} 秒出现较高削波比例；${t.quietSeconds??'未检查'} 秒电平很低。此指标不能判断底噪好坏。${t.readError?'读取异常：'+t.readError:''}`;$('#quiet').disabled=t.quietSeek===null;$('#playError').textContent='';if(changed){audio.pause();audio.src=t.uri;audio.load()}render();const active=$('#list .row.active');active?.scrollIntoView({block:'nearest'});if(play)audio.play().catch(()=>{$('#playError').textContent='无法直接播放 Y: 盘文件；请告诉我，我会改成本地试听副本。'})}
function next(delta,unrated=false){if(!visible.length)return;let pos=visible.indexOf(current);for(let k=1;k<=visible.length;k++){const i=visible[(pos+delta*k+visible.length*10)%visible.length];if(!unrated||!state[tracks[i].id]?.decision){choose(i);return}}}
function decide(decision){if(current<0)return;const t=tracks[current];state[t.id]={decision,comment:$('#comment').value,ranges:$('#ranges').value,updatedAt:new Date().toISOString()};save();render();if($('#auto').checked&&decision)next(1,true)}
$('#list').onclick=e=>{const row=e.target.closest('.row');if(row)choose(Number(row.dataset.index))};$('#list').onkeydown=e=>{if(e.key==='Enter'){const row=e.target.closest('.row');if(row)choose(Number(row.dataset.index))}};
['search','group','filter'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));
$('#prev').onclick=()=>next(-1);$('#next').onclick=()=>next(1);$('#nextUnrated').onclick=()=>next(1,true);
document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>decide(b.dataset.decision));
['comment','ranges'].forEach(field=>$('#'+field).oninput=()=>{if(current<0)return;const id=tracks[current].id;state[id]={...(state[id]||{}),[field]:$('#'+field).value};save()});
document.querySelectorAll('[data-seek]').forEach(b=>b.onclick=()=>{if(current<0)return;const v=Number(b.dataset.seek);const go=()=>{audio.currentTime=v<1?(audio.duration||tracks[current].seconds)*v:v;audio.play()};if(audio.readyState)go();else audio.addEventListener('loadedmetadata',go,{once:true})});
$('#quiet').onclick=()=>{if(current<0)return;audio.currentTime=Math.max(0,tracks[current].quietSeek-3);audio.play()};
document.onkeydown=e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if([' ','j','l','n','1','2','3','4'].includes(k))e.preventDefault();if(k===' ')audio.paused?audio.play():audio.pause();if(k==='j')audio.currentTime=Math.max(0,audio.currentTime-30);if(k==='l')audio.currentTime=Math.min(audio.duration||1e9,audio.currentTime+30);if(k==='n')next(1,true);if(k==='1')decide('keep');if(k==='2')decide('mood');if(k==='3')decide('partial');if(k==='4')decide('reject')};
audio.onended=()=>{if($('#auto').checked)next(1,true)};audio.onerror=()=>{$('#playError').textContent='音频加载失败；Y: 盘可能未连接。'};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({experiment:'guqin_full_recordings_v1',source:'Y:\Music\古琴曲',state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='古琴整曲筛选反馈.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#import').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!data.state||typeof data.state!=='object')throw Error('格式不符');state={...state,...data.state};save();render();if(current>=0)choose(current,false)}catch(err){alert('导入失败：'+err.message)}e.target.value=''};
render();choose(visible.find(i=>!state[tracks[i].id]?.decision)??visible[0]??0,false);
